name: RustDesk RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install RDP and RustDesk
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-terminal xrdp wget
          sudo systemctl enable xrdp
          sudo systemctl start xrdp

          # Install RustDesk
          wget https://github.com/rustdesk/rustdesk/releases/download/1.3.8/rustdesk-1.3.8-x86_64.deb
          sudo dpkg -i rustdesk-1.3.8-x86_64.deb || sudo apt -f install -y
          
          # Start RustDesk
          nohup rustdesk > /dev/null 2>&1 &

          echo "RustDesk is now running!"
