name: Windows RDP
on: workflow_dispatch

jobs:
  build:
    name: Start RDP Session
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Setup RDP
        run: |
          net user winmine /add
          net user winmine 24498
          net localgroup administrators winmine /add
          reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
          Enable-PSRemoting -Force
          Set-ItemProperty "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name fDenyTSConnections -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Restart-Computer -Force
      
      
      - name: Get Public IP
        run: curl ifconfig.me

      - name: Enable RDP
        run: |
          reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
          netsh advfirewall firewall set rule group="Remote Desktop" new enable=Yes

      - name: Set RDP User Password
        run: |
          net user winmine 24498

      - name: Keep RDP Running
        run: |
          while ($true) { Start-Sleep -Seconds 3600 }

          




